// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "lensfrex",
            "email": "lensferno@outlook.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add-countdown": {
            "post": {
                "description": "添加一条todo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    ""
                ],
                "summary": "添加一条todo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "description": "todo信息",
                        "name": "object",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/http.TodolistReqItem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "uint64"
                        }
                    }
                }
            }
        },
        "/del-countdown": {
            "get": {
                "description": "删除一个todo项",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    ""
                ],
                "summary": "删除一个todo项",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "欲删除的id",
                        "name": "uuid",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/list-countdown": {
            "get": {
                "description": "获取用户当前的todolist",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    ""
                ],
                "summary": "获取用户当前的todolist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {}
            }
        },
        "/modify-countdown": {
            "get": {
                "description": "复制一个todo项（添加分享的倒计时）",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    ""
                ],
                "summary": "复制一个todo项（添加分享的倒计时）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "欲添加的id",
                        "name": "uuid",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "http.TodolistReqItem": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "武科大助手todolist模块（原倒计时模块）",
	Description:      "武科大助手todolist模块（原倒计时模块）",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
